// Simple array with one animal per letter of the alphabet
export const animalByLetter = [
    'Alligator',
    'Brown Bear',
    'Chicken',
    'Duck',
    'Elephant',
    'Fish',
    'Gorilla',
    'Horse',
    'Iguana',
    'Jaguar',
    'Kangaroo',
    'Lioness',
    'Zonkey',
    'Ponkey',
    'Newt',
    'Octopus',
    'Penguin',
    'Quail',
    'Rabbit',
    'Snake',
    'Tiger',
    'Umbrella Bird',
    'Vulture',
    'Whale',
    'X-ray Fish',
    'Yak',
    'Zebra'
]


export const animalsByLetter = {
  A: ['Aardvark', 'Alligator', 'Antelope', 'Armadillo', 'Alpaca', 'Ant', 'Ape', 'Axolotl'],
  B: ['Bear', 'Butterfly', 'Bee', 'Buffalo', 'Badger', 'Bat', 'Blue Jay', 'Bobcat'],
  C: ['Cat', 'Cow', 'Chicken', 'Cheetah', 'Camel', 'Crab', 'Crocodile', 'Chameleon'],
  D: ['Dog', 'Duck', 'Deer', 'Dolphin', 'Dragonfly', 'Dove', 'Donkey', 'Dingo'],
  E: ['Elephant', 'Eagle', 'Eel', 'Emu', 'Elk', 'Earthworm', 'Echidna', 'Egret'],
  F: ['Fox', 'Frog', 'Fish', 'Falcon', 'Flamingo', 'Ferret', 'Fly', 'Firefly'],
  G: ['Giraffe', 'Goat', 'Gorilla', 'Goldfish', 'Goose', 'Gecko', 'Grasshopper', 'Gazelle'],
  H: ['Horse', 'Hippo', 'Hamster', 'Hawk', 'Hedgehog', 'Hummingbird', 'Hyena', 'Hermit Crab'],
  I: ['Iguana', 'Ibis', 'Impala', 'Insect', 'Inchworm', 'Ibex', 'Isopod', 'Iguanodon'],
  J: ['Jaguar', 'Jellyfish', 'Jay', 'Jackal', 'Jackrabbit', 'Jaguar', 'Jewel Beetle', 'Junco'],
  K: ['Kangaroo', 'Koala', 'Kiwi', 'Kingfisher', 'Komodo Dragon', 'Kestrel', 'Kudu', 'Killer Whale'],
  L: ['Lion', 'Leopard', 'Llama', 'Lobster', 'Ladybug', 'Lemur', 'Lizard', 'Lynx'],
  M: ['Monkey', 'Mouse', 'Moose', 'Mole', 'Mantis', 'Moth', 'Manatee', 'Meerkat'],
  N: ['Newt', 'Nightingale', 'Narwhal', 'Numbat', 'Nuthatch', 'Nudibranch', 'Nighthawk', 'Nematode'],
  O: ['Octopus', 'Owl', 'Otter', 'Ostrich', 'Orangutan', 'Ocelot', 'Ox', 'Oriole'],
  P: ['Penguin', 'Panda', 'Parrot', 'Pig', 'Peacock', 'Polar Bear', 'Porcupine', 'Platypus'],
  Q: ['Quail', 'Queen Bee', 'Quetzal', 'Quokka', 'Quoll', 'Queen Snake', 'Quelea', 'Quahaug'],
  R: ['Rabbit', 'Rhinoceros', 'Robin', 'Raccoon', 'Rat', 'Raven', 'Ray', 'Reindeer'],
  S: ['Snake', 'Shark', 'Sheep', 'Squirrel', 'Spider', 'Starfish', 'Swan', 'Seal'],
  T: ['Tiger', 'Turtle', 'Turkey', 'Toucan', 'Tarantula', 'Toad', 'Termite', 'Trout'],
  U: ['Umbrella Bird', 'Urial', 'Urchin', 'Upupa', 'Uakari', 'Umbrellabird', 'Unicorn Fish', 'Underwing Moth'],
  V: ['Vulture', 'Viper', 'Vicuña', 'Vampire Bat', 'Vole', 'Vervet Monkey', 'Vulpes', 'Vireo'],
  W: ['Wolf', 'Whale', 'Worm', 'Walrus', 'Woodpecker', 'Weasel', 'Wasp', 'Wallaby'],
  X: ['X-ray Fish', 'Xerus', 'Xenops', 'Xingu River Ray', 'Xoloitzcuintli', 'Xylocopa', 'Xantus Hummingbird', 'Xenarthra'],
  Y: ['Yak', 'Yellowfin Tuna', 'Yabby', 'Yellow Jacket', 'Yellowhammer', 'Yeti Crab', 'Yapok', 'Yellow Warbler'],
  Z: ['Zebra', 'Zebu', 'Zonkey', 'Zorilla', 'Zander', 'Zebrafish', 'Zokor', 'Zorse']
};